# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(392, 361)
        Form.setStyleSheet("background:#78EE9A")
        self.btnKNn = QtWidgets.QPushButton(Form)
        self.btnKNn.setGeometry(QtCore.QRect(90, 100, 211, 41))
        self.btnKNn.setStyleSheet("background: #3FEEC6; \n"
"border-radius: 10%; \n"
"border:1px solid;")
        self.btnKNn.setObjectName("btnKNn")
        self.btnMetricas = QtWidgets.QPushButton(Form)
        self.btnMetricas.setGeometry(QtCore.QRect(90, 40, 211, 41))
        self.btnMetricas.setStyleSheet("background: #3FEEC6; \n"
"border-radius: 10%; \n"
"border:1px solid;\n"
"")
        self.btnMetricas.setObjectName("btnMetricas")
        self.btnNeurona = QtWidgets.QPushButton(Form)
        self.btnNeurona.setGeometry(QtCore.QRect(90, 160, 211, 41))
        self.btnNeurona.setStyleSheet("background: #3FEEC6; \n"
"border-radius: 10%; \n"
"border:1px solid;")
        self.btnNeurona.setObjectName("btnNeurona")
        self.btnProyecto = QtWidgets.QPushButton(Form)
        self.btnProyecto.setGeometry(QtCore.QRect(90, 220, 211, 41))
        self.btnProyecto.setStyleSheet("background: #3FEEC6; \n"
"border-radius: 10%; \n"
"border:1px solid;")
        self.btnProyecto.setObjectName("btnProyecto")
        self.lblNames = QtWidgets.QLabel(Form)
        self.lblNames.setGeometry(QtCore.QRect(0, 270, 391, 91))
        self.lblNames.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblNames.setText("")
        self.lblNames.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNames.setObjectName("lblNames")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnKNn.setText(_translate("Form", "Clasificador KNN"))
        self.btnMetricas.setText(_translate("Form", "Clasificador por Metricas"))
        self.btnNeurona.setText(_translate("Form", "Perceptron"))
        self.btnProyecto.setText(_translate("Form", "Proyecto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
